

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marvel
    username: postgres
    password: root

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show_sql: true



    hibernate:
      ddl-auto: update  # Hibernate ddl auto (create, create-drop, validate, update)
      format_sql: true
      use_sql_comments: true


# Enable to print variables
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace

#        SQL: DEBUG